var casId = os_type == os_android ? "com.company.product" : "1000000000"
CAS_initialize(casId, CAS_AD_TYPE_REWARDED | CAS_AD_TYPE_INTERSTITIAL, CAS_AUDIENCE_CHILDREN, CAS_CONSENT_STATUS_ACCEPTED, CAS_CCPA_STATUS_OPT_IN_SALE, 1)
